# Generated by Django 2.2 on 2021-09-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adword_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='Null', max_length=200)),
                ('product', models.TextField(default='Null', max_length=255)),
                ('campaign_name', models.TextField(default='Null', max_length=255)),
                ('ad_set_name', models.CharField(default='Null', max_length=200)),
                ('ad_name', models.CharField(default='Null', max_length=200)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('spends', models.IntegerField(default=0)),
                ('date1', models.CharField(default='Null', max_length=200)),
                ('srno', models.IntegerField(default=0)),
                ('source', models.CharField(default='Null', max_length=200)),
                ('headline1', models.CharField(default='Null', max_length=200)),
                ('headline2', models.CharField(default='Null', max_length=200)),
                ('description', models.CharField(default='Null', max_length=200)),
                ('path1', models.CharField(default='Null', max_length=200)),
                ('path2', models.CharField(default='Null', max_length=200)),
                ('datetobeconsidered', models.CharField(default='Null', max_length=200)),
                ('icogzclientid', models.IntegerField(default=0)),
                ('imageurl', models.CharField(default='Null', max_length=200)),
                ('reach', models.CharField(default='Null', max_length=200)),
                ('modifiedon', models.CharField(default='Null', max_length=200)),
                ('location', models.CharField(default='Null', max_length=200)),
                ('device', models.CharField(default='Null', max_length=200)),
                ('state', models.CharField(default='Null', max_length=200)),
                ('views', models.IntegerField(default=0)),
                ('view_rate', models.IntegerField(default=0)),
                ('country', models.CharField(default='Null', max_length=200)),
                ('uniqueclicks', models.IntegerField(default=0)),
                ('video_15_sec_watched', models.IntegerField(default=0)),
                ('video_30_sec_watched', models.IntegerField(default=0)),
                ('inline_link_clicks', models.IntegerField(default=0)),
                ('inline_post_engagement', models.IntegerField(default=0)),
                ('campaigntype', models.CharField(default='Null', max_length=200)),
                ('mobileappinstall', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'adword_data',
            },
        ),
        migrations.CreateModel(
            name='app_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('media_source', models.CharField(max_length=200)),
                ('campaign', models.CharField(max_length=200)),
                ('source_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'app_data',
            },
        ),
        migrations.CreateModel(
            name='ios_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('media_source', models.CharField(max_length=200)),
                ('campaign', models.CharField(max_length=200)),
                ('source_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ios_data',
            },
        ),
    ]
