# Generated by Django 3.2.5 on 2021-08-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('media_source', models.CharField(max_length=200)),
                ('campaign', models.CharField(max_length=200)),
                ('source_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'app_data',
            },
        ),
    ]
