# Generated by Django 2.2 on 2021-09-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adword_data',
            name='ad_name',
            field=models.CharField(default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='adword_data',
            name='ad_set_name',
            field=models.CharField(default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='adword_data',
            name='date',
            field=models.CharField(default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='adword_data',
            name='date1',
            field=models.CharField(default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='adword_data',
            name='inline_link_clicks',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AlterField(
            model_name='adword_data',
            name='inline_post_engagement',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AlterField(
            model_name='adword_data',
            name='mobileappinstall',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AlterField(
            model_name='adword_data',
            name='uniqueclicks',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AlterField(
            model_name='adword_data',
            name='video_15_sec_watched',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AlterField(
            model_name='adword_data',
            name='video_30_sec_watched',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AlterField(
            model_name='adword_data',
            name='view_rate',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AlterField(
            model_name='adword_data',
            name='views',
            field=models.CharField(default='Null', max_length=200),
        ),
    ]
