# Generated by Django 3.2.5 on 2021-08-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_data',
            name='country',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='app_data',
            name='date',
            field=models.TextField(max_length=500),
        ),
    ]
