# Generated by Django 2.2 on 2021-09-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_analysis', '0002_auto_20210908_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adword_data',
            name='icogzclientid',
            field=models.CharField(default='Null', max_length=200),
        ),
    ]
