# Generated by Django 3.2.6 on 2021-08-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_analysis', '0002_auto_20210802_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='adword_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.TextField(max_length=500)),
                ('Campaign_Name', models.CharField(max_length=500)),
                ('Ad_Set_Name', models.CharField(max_length=200)),
                ('Ad_Name', models.CharField(max_length=200)),
                ('Impressions', models.CharField(max_length=200)),
                ('Clicks', models.CharField(max_length=200)),
                ('Conversions', models.CharField(max_length=200)),
                ('Spends', models.CharField(max_length=200)),
                ('Source', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('DateToBeConsidered', models.CharField(max_length=200)),
                ('IcogzClientID', models.CharField(max_length=200)),
                ('ImageUrl', models.CharField(max_length=200)),
                ('Reach', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('Views', models.CharField(max_length=200)),
                ('View', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('UniqueClicks', models.CharField(max_length=200)),
                ('video_15_sec_watched', models.CharField(max_length=200)),
                ('video_30_sec_watched', models.CharField(max_length=200)),
                ('inline_link_clicks', models.CharField(max_length=200)),
                ('inline_post_engagement', models.CharField(max_length=200)),
                ('CampaignType', models.CharField(max_length=200)),
                ('MobileAppInstall', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'adword_data',
            },
        ),
    ]
