# Generated by Django 2.2 on 2021-09-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_analysis', '0003_auto_20210908_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adword_data',
            name='campaign_name',
            field=models.CharField(default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='adword_data',
            name='product',
            field=models.CharField(default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='adword_data',
            name='srno',
            field=models.CharField(default='Null', max_length=255),
        ),
    ]
