# Generated by Django 2.2 on 2021-09-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_analysis', '0003_adword_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ios_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('media_source', models.CharField(max_length=200)),
                ('campaign', models.CharField(max_length=200)),
                ('source_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ios_data',
            },
        ),
        migrations.DeleteModel(
            name='adword_data',
        ),
        migrations.AlterField(
            model_name='app_data',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
