# Generated by Django 2.2 on 2021-09-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_analysis', '0005_auto_20210908_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_data',
            name='install',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ios_data',
            name='install',
            field=models.IntegerField(default=0),
        ),
    ]
