# Generated by Django 2.2 on 2021-09-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_analysis', '0006_auto_20210908_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(default='Null', max_length=255)),
                ('event_count', models.IntegerField(default=0)),
                ('people_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'subscription_method',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_plan', models.CharField(default='Null', max_length=255)),
                ('event_count', models.IntegerField(default=0)),
                ('people_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('sale', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'subscription_plan',
            },
        ),
    ]
